name: GHRELEASE

on:
  push:
    branches:
      - main  # Replace with your default branch if it's not 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'



      - name: Install dependencies
        run: npm ci  # Use npm ci for installing exact versions from package-lock.json

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GHRELEASE }}
